= System-Wide Requirements: {project-name}
Marc-Oliver Tittel <s82452@htw-dresden.de>; Manuel Hartmann <s83688@htw-dresden.de>; Charlotte Geißler <s82397@htw-dresden.de>; Jan Trodler <s83832@htw-dresden.de>; Lukas Kouba <s83783@htw-dresden.de>; Luc Sowodniok <s83864@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute

== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt E1 Kalenderintegration spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten. <<#use-case_model, Use-Case Model>>

//xref:use-case_model.adoc[Use-Case Model]
<<use-case_model.adoc, Use-Case Model>>

// Verknüpfung zum laufen bringen 

== Systemweite funktionale Anforderungen

* *SWFA-1:* Das System muss sicherstellen, dass der Benutzer authentifiziert ist.
** Die Validierung dre Daten erfolgt anhand existierender Anmeldedaten bei den Kalenderplatformen.
* *SWFA-2:* Das System muss in der Lage sein, Tage mit Terminen, hervorzuheben. 
** Zur Überprüfung wird ein Testtermin angelegt, dieser muss hervorgehoben werden. 
* *SWFA-3:* Das System muss die Login-Daten der Nutzer vor Diebstahl schützen.
** Zur Überprüfung gibt es einen Versuch Testzugangsdaten auszulesen. 
* *SWFA-4:* Das System muss die Zugangsdaten und sonstige Dateninhalte des Nutzers dauerhaft speichern.
** Zur Überprüfung wird das System neu gestartet und getestet, ob die bereits eingefügten Daten weiterhin vollständig sind. 
* *SWFA-5:* Das System muss die gesammelten Daten auf geeignete Weise exportieren können. 
** Zur Überprüfung wird ein Datensatz exportiert. Alle relevanten Daten müssen enthalten sein. 
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz


== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
* *NFAU-1:* Das Tool soll in deutscher Sprache verfügbar sein.
* *NFAU-2:* Der im Tool dargestellte Kalender muss gut erkennbar und leicht bedienbar sein.
** Zur Überprüfung benutzt ein Testnutzer das Tool ohne vorherige Kenntnisse über das Tool. 
* *NFAU-3:* Die kompatiblen Kalenderanbieter sollen im Tool einfach auswählbar sein.
** Zur Überprüfung melden sich Testnutzer mit verschiedenen Kalenderanbietern an.
* *NFAU-4:* Das Tool Bearbeitungen im Kalendereintrag nur im Bereich "Notizen" erlauben. Alle anderen Daten sind statisch und werden nur übermittelt (Tag, Zeit, Ort, Teilnehmer, Titel, ...).  
** Zur Überprüfung versucht ein Testnutzer die festen Daten zu ändern. 

//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)

=== Zuverlässigkeit (Reliability)
* *NFAR-1:* Das Tool soll robust gegen Abstürze.
** Zur Überprüfung wird die Internetverbindung getrennt und/oder das System wird unerwartet heruntergefahren.
* *NFAR-2:* Die Sicherheit und der Schutz vor Verlust der Daten soll das Tool sicherstellen.
* *NFAR-3:* Die Erreichbarkeit des Tools soll nahezu zu jederzeit gewährleistet werden können.
** Zur Überprüfung wird das Tool von Testnutzern zu zufälligen Zeitpunkten angesprochen.
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.

=== Effizienz (Performance)
* *NFAP-1:* Das Tool muss robust gegen einen Ausfall bei einer hohen Anzahl gleichzeitiger Nutzer sein.
** Zur Überprüfung wird das Tool von Testnutzern zum gleichen Zeitpunkten angesprochen.
* *NFAP-2:* Das Tool soll eine sofortige Synchronisation der zugehörigen Systeme ermöglichen.
** Zur Überprüfung starten die Testnutzer das Tool zufällig neu.
// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.

=== Wartbarkeit (Supportability)
* *NFAS-1:* Das Tool soll für folgende Browser verfügbar sein: Safari, Chrome, Edge, Firefox, Opera.
** Zur Überprüfung rufen die Testnutzer das Tool in verschiedenen Browsern auf. 
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.


== Zusätzliche Anforderungen

=== Einschränkungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Die Verwaltung des Sourcecodes und der Dokumentation muss mittels GitHub erfolgen.
* Folgende Programmiersprachen sind vorgegeben:
** Python (Django Server)
** HTML
** GraphQL Endpunkt
** Frontend: Vue.js Framework
* Unterstützte Kalendersysteme:
** Microsoft
** Google
//* Ressourcenbegrenzungen
//* zu nutzende Komponenten / Bibliotheken / Frameworks
//* Vorgaben für die Programmiersprache
//* zu unterstützende Plattformen / Betriebssysteme
//* Physische Begrenzungen für Hardware, auf der das System betrieben werden soll

=== Organisatorische Randbedingungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren

* Das System muss unbefugte Dateeinsichtnahme wirksam verhindern. 

=== Rechtliche Anforderungen
* Der Kunde muss über eine mögliche Speicherung von Nutzungsdaten informiert werden.
* Eine etwaige Datenschutzerklärung muss beim Login vorliegen und vor der Nutzung durch
Kunden anerkannt werden. 
* Das System muss den Datenschutzverordnungen von Speechmind und den Kalenderanbietern entsprechen. 
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
//* Lizensierung der Anwendung
//* Datenschutz
