= Vision: {project-name}
Marc-Oliver Tittel <s82452@htw-dresden.de>; Manuel Hartmann <s83688@htw-dresden.de>; Charlotte Geißler <s82397@htw-dresden.de>; Jan Trodler <s83832@htw-dresden.de>; Lukas Kouba <s00000@htw-dresden.de>; Luc Sowodniok <s83864@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten der {project-name} zu sammeln, zu analysieren und zu definieren. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die  Details, wie die {project-name} diese Bedarfe erfüllt, werden in der Use-Case und Supplementary Specification beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf die {project-name}, das von Gruppe E1 entwickelt wird. Das System wird es SpeechMind erlauben, die Meetingdokumentation in den passenden Kalender automatisch einzutragen, um auf vergangene Meetings, samt Dokumentation, besser zugreifen zu können.

=== Definitionen, Akronyme und Abkürzungen
//Verweis passend zum Belegabgabe-Template se1_belegabgabe_t00.adoc
Siehe <<#glossary, Glossar>>.

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)


== Positionierung

=== Fachliche Motivation
Der Kalender spielt in der Arbeitswelt eine enorm große Rolle, da darüber Termine, Meetings und
die gesamte Organisation des Arbeits- und Privatlebens stattfindet. Die Zielgruppe des SpeechMind
Studios sind Product Owner in Unternehmen, die Software entwickeln.
In Kalendern sind Telefonnummern und Links zu Onlinemeetings, die Agenda des nächsten Termins
oder Terminpriorisierungen vermerkt. Diese Informationen haben einen hohen Mehrwert in
einem automatisierten System, da über die zusätzlichen Informationen Funktionen gestartet werden
können oder im nachhinein erneut wichtige Punkte/Informationen entnommen werden können.
Mit SpeechMind wollen wir diese Kalendereinträge sowohl auslesen, damit nach dem Ende eines
Meetings automatisch die Audioaufnahme durch uns ausgewertet werden kann. Darüber hinaus ist
jedoch auch geplant diese Einträge als Dokumentationselement zu nutzen und mit den generierten
Daten anzureichern. Somit muss der Product Owner nicht erst die verschiedenen Systeme öffnen,
um schnell an aktuelle oder vergangene Dokumentation zu kommen, sondern hat all diese Informationen
kurz und prägnant in einem Kalendereintrag verknüpft.


=== Problem Statement
//Stellen Sie zusammenfassend das Problem dar, das mit diesem Projekt gelöst werden soll. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
| Das Problem | Meetingdokumentation (zu erstellen und) in den Kalender zu integrieren
| betrifft | Auftraggeber, Kunden, Gesetzgeber, Projektteam, Django Server
| die Auswirkung davon ist | hoher Zeitaufwand, Fehleranfälligkeit, kein zeitlicher Kontext bei Meetingnachbereitung
| eine erfolgreiche Lösung wäre |  effiziente und schnelle Auswertung des Meetings und Zugriff via Kalender
|===

////
Beispiel:
[cols="1,3"]
|===
|Das Problem | aktuelle Informationen zum Stundenplan und Noten einfach zu erhalten
|betrifft | Studierende der HTW Dresden
|die Auswirkung davon ist | umständliche und aufwändige Suche nach Noten, Zeiten und Räumen
|eine erfolgreiche Lösung wäre | die Zusammenführung und benutzer-individuelle Darstellung auf einem mobilen Endgerät
|===
////

=== Positionierung des Produkts
//Ein Positionierung des Produkts beschreibt das Einsatzziel der Anwendung und die Bedeutung das Projekts an alle beteiligten Mitarbeiter.

//Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
| Für | Softwareentwickler
| der / die | effizienter auf Meetingdokumentationen zugreifen wollen
| Das Produkt / die Lösung ist ein | Webanwendung
| Die / Das | alle Informationen von einem Meeting mit einem Kalendereintrag verknüpft
| Im Gegensatz zu | manueller Eingabe
| Unser Produkt | ermöglicht eine einfache Integration Ihrer Meetingdokumentation in einen Kalender Ihrer Wahl über die SpeechMind Seite
|===

////
Beispiel Produkt:
|===
| Für | Studierende der HTW
| die | die ihren Studienalltag effizienter organisieren möchten
| Das Produkt ist eine | mobile App für Smartphones
| Die | für den Nutzer Informationen zum Stundenplan und Noten darstellt
| Im Gegensatz zu | Stundenplänen der Website und HIS-Noteneinsicht
| Unser Produkt | zeigt nur die für den Nutzer relevanten Informationen komfortabel auf dem Smartphone an.
|===
////


== Stakeholder Beschreibungen

=== Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
| Name | Beschreibung | Verantwortlichkeiten

| Auftraggeber
| SpeechMind
| Ansprechpartner für das Projekt der die Anforderungen an das Tool festlegt, Instandhaltung

| Kunden
| Nutzer des SpeechMind Systems
| Arbeiten mit dem Tool

| Gesetzgeber
| 
| Gibt Vorschriften für Datenschutz u.ä.

| Projektteam
| Studenten der HTW Dresden
| Entwicklung des Tools

| Plattform
| Django Server
| Speicherung der Daten
|===

=== Benutzerumgebung
Beschreiben Sie die Arbeitsumgebung des Nutzers. Hier sind einige Anregungen:

//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Anzahl der Personen, die an der Erfüllung der Aufgabe beteiligt sind. Ändert sich das?
. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
. Internetverbindung muss gewährleistet sein
. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.


== Produkt-/Lösungsüberblick

=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten und das geplante Release für die Veröffentlichung der Features an.

[%header, cols="4,1,4,1"]
|===    
| Bedarf | Priorität | Features | Geplantes Release
| Authentifizierung des Nutzenden in der entsprechenden Kalendersoftware | hoch | Ermöglicht den Zugriff auf den selbstgewählten Kalender | mit Veröffentlichung
| DB-Modell für Kalenderintegration  | hoch | universell | xx
| Sync der Kalendereinträge in das SpeechMind Studio | hoch | Abruf des Kalenders in SpeechMind Studio | mit Veröffentlichung
| Erstellen der Kalendereinträge | hoch | Nach Meeting (Kalendereintrag für Meetingdokumentation) | mit Veröffentlichung
| Nachbearbeiten der Kalendereinträge | mittel | nachträgliche Ergänzung von Informationen | xx
|===


== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Backend: Django Server
.. Endpunkt zum Entwicklungsserver wird gestellt
. GraphQL Endpunkt
. Frontend: Vue.js Framework

Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen 

. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die nicht von den genannten Features erfasst werden.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen-
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.


